@tool
class_name StorePresets
extends RefCounted

## The single source of truth for storefront image specs.
##
## Everything else in this tool reads from [member STORES] — the inspector
## dropdowns, the output folder names and the generator's alpha handling. To
## support a new storefront or a new asset, add an entry here and nothing else
## needs to change.
##
## Every size below is quoted from the storefront's own documentation; the URL
## in each store's "docs" field is where it came from. Sizes do go stale, so
## check the docs link before a real submission.

## Preset id used by a [StoreAsset] that sets its own size instead of taking
## one from this table.
const CUSTOM_ID := ""

## The image must be fully opaque. The generator drops the alpha channel and
## warns if anything was transparent.
const ALPHA_NONE := "none"
## The image is meant to sit on top of other art, so it wants a transparent
## background. The generator warns if the result is fully opaque.
const ALPHA_REQUIRED := "required"
## The storefront accepts either.
const ALPHA_OPTIONAL := "optional"

## Separator between the store id and the asset id in a preset id, e.g.
## "steam/library_logo".
const ID_SEPARATOR := "/"

const STORES := {
	"steam": {
		"label": "Steam",
		"folder": "steam",
		"docs": "https://partner.steamgames.com/doc/store/assets/standard",
		"assets": {
			"header_capsule": {
				"label": "Header Capsule",
				"size": Vector2i(920, 430),
				"required": true,
				"note": "No text beyond the title. Smaller sizes are generated by Steam.",
			},
			"small_capsule": {
				"label": "Small Capsule",
				"size": Vector2i(462, 174),
				"required": true,
				"note": "Logo must stay legible down to the 120x45 auto-generated size.",
			},
			"main_capsule": {
				"label": "Main Capsule",
				"size": Vector2i(1232, 706),
				"required": true,
				"note": "Front page carousel.",
			},
			"vertical_capsule": {
				"label": "Vertical Capsule",
				"size": Vector2i(748, 896),
				"required": true,
				"note": "Seasonal sale and sale pages.",
			},
			"page_background": {
				"label": "Page Background",
				"size": Vector2i(1438, 810),
				"required": false,
				"note": "Ambient art. Steam generates one from your last screenshot if omitted.",
			},
			"bundle_header": {
				"label": "Bundle Header",
				"size": Vector2i(707, 232),
				"required": false,
				"note": "Only needed if you sell a bundle.",
			},
			"library_capsule": {
				"label": "Library Capsule",
				"size": Vector2i(600, 900),
				"required": true,
				"note": "PNG. Steam generates the 300x450 half size.",
			},
			"library_header": {
				"label": "Library Header",
				"size": Vector2i(920, 430),
				"required": true,
				"note": "PNG. Shown in the client library and Recent Games.",
			},
			"library_hero": {
				"label": "Library Hero",
				"size": Vector2i(3840, 1240),
				"required": true,
				"note": "PNG. No text. Only the centred 860x380 safe area survives cropping.",
			},
			"library_logo": {
				"label": "Library Logo",
				"size": Vector2i(1280, 720),
				"required": true,
				"alpha": ALPHA_REQUIRED,
				"note": "PNG on a transparent background. 1280 wide and/or 720 tall; sits on the hero.",
			},
			"community_icon": {
				"label": "Community Icon",
				"size": Vector2i(184, 184),
				"required": true,
				"note": "",
			},
			"screenshot": {
				"label": "Screenshot",
				"size": Vector2i(1920, 1080),
				"required": true,
				"note": "At least 5, showing actual gameplay. 1920x1080 is the minimum.",
			},
		},
	},
	"itch": {
		"label": "itch.io",
		"folder": "itch",
		"docs": "https://itch.io/docs/creators/getting-started",
		"assets": {
			"cover": {
				"label": "Cover Image",
				"size": Vector2i(630, 500),
				"required": true,
				"note": "Must be 315:250. 315x250 is the minimum; 630x500 is itch's suggested size.",
			},
			"banner": {
				"label": "Page Banner",
				"size": Vector2i(960, 400),
				"required": false,
				"note": "itch publishes no official banner size. 960x400 is the widely used community template size.",
			},
			"screenshot": {
				"label": "Screenshot",
				"size": Vector2i(1920, 1080),
				"required": false,
				"note": "Any size is accepted. itch recommends uploading 3 to 5.",
			},
		},
	},
	"epic": {
		"label": "Epic Games Store",
		"folder": "epic",
		"docs": "https://dev.epicgames.com/docs/epic-games-store/sales-and-marketing/marketing/storefront-media-guide",
		"assets": {
			"product_logo": {
				"label": "Product Logo",
				"size": Vector2i(960, 540),
				"required": true,
				"alpha": ALPHA_REQUIRED,
				"note": "PNG, max 1 MB. Epic mandates PNG here because the logo overlays other art.",
			},
			"offer_landscape": {
				"label": "Offer Image - Landscape",
				"size": Vector2i(2560, 1440),
				"required": true,
				"note": "Needed as both a general image and a library image.",
			},
			"offer_portrait": {
				"label": "Offer Image - Portrait",
				"size": Vector2i(1200, 1600),
				"required": true,
				"note": "Checkout flow and wishlist notifications.",
			},
			"media_carousel_image": {
				"label": "Media Carousel Image",
				"size": Vector2i(1920, 1080),
				"required": true,
				"note": "Max 4 MB. Epic recommends at least five carousel assets including a video.",
			},
			"about_image": {
				"label": "About Section Image",
				"size": Vector2i(1920, 1080),
				"required": true,
				"note": "Spec is 'at least 700 px wide', max 4 MB. 1920x1080 is a safe choice.",
			},
			"about_additional_image": {
				"label": "About Section Additional Image",
				"size": Vector2i(1920, 1080),
				"required": false,
				"alpha": ALPHA_NONE,
				"note": "JPG, max 1 MB, up to 20 of them.",
			},
			"social_preview": {
				"label": "Social Preview",
				"size": Vector2i(1200, 1200),
				"required": false,
				"alpha": ALPHA_NONE,
				"note": "JPG only, max 4 MB. Shown when the store link is posted on social media.",
			},
		},
	},
	"gog": {
		"label": "GOG",
		"folder": "gog",
		"docs": "https://docs.gog.com/basic-game-assets/",
		# GOG does not publish its store capsule sizes: partners are pointed at
		# templates and an Asset Rendering Tool behind the developer portal. Only
		# the key art minimum and the Galaxy artwork sizes below are public, so
		# treat this store as a starting point rather than a complete set.
		"assets": {
			"key_art": {
				"label": "Key Art",
				"size": Vector2i(1920, 1080),
				"required": true,
				"note": "GOG's checklist asks for key art and logo at min. 1920x1080 as a layered .psd.",
			},
			"galaxy_tile": {
				"label": "Galaxy Tile",
				"size": Vector2i(342, 482),
				"required": false,
				"note": "Size from GOG's public Galaxy artwork support article.",
			},
			"galaxy_background": {
				"label": "Galaxy Background",
				"size": Vector2i(1600, 670),
				"required": false,
				"note": "Size from GOG's public Galaxy artwork support article.",
			},
			"galaxy_icon": {
				"label": "Galaxy Icon",
				"size": Vector2i(112, 112),
				"required": false,
				"note": "Size from GOG's public Galaxy artwork support article.",
			},
		},
	},
	"google_play": {
		"label": "Google Play",
		"folder": "google_play",
		"docs": "https://support.google.com/googleplay/android-developer/answer/9866151",
		"assets": {
			"app_icon": {
				"label": "App Icon",
				"size": Vector2i(512, 512),
				"required": true,
				"note": "32-bit PNG with alpha, max 1024 KB. Play applies its own mask.",
			},
			"feature_graphic": {
				"label": "Feature Graphic",
				"size": Vector2i(1024, 500),
				"required": true,
				"alpha": ALPHA_NONE,
				"note": "No alpha channel. Keep text inside the centred 924x400 safe zone.",
			},
			"phone_screenshot_portrait": {
				"label": "Phone Screenshot - Portrait",
				"size": Vector2i(1080, 1920),
				"required": true,
				"alpha": ALPHA_NONE,
				"note": "Two minimum to publish, eight maximum.",
			},
			"phone_screenshot_landscape": {
				"label": "Phone Screenshot - Landscape",
				"size": Vector2i(1920, 1080),
				"required": false,
				"alpha": ALPHA_NONE,
				"note": "16:9. Use instead of the portrait size for landscape games.",
			},
			"tablet_screenshot_landscape": {
				"label": "Tablet Screenshot - Landscape",
				"size": Vector2i(2560, 1440),
				"required": false,
				"alpha": ALPHA_NONE,
				"note": "Four minimum if you list tablet support. Any 16:9 size from 1080 to 7680 px.",
			},
		},
	},
	"app_store": {
		"label": "Apple App Store",
		"folder": "app_store",
		"docs": "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications/",
		"assets": {
			"app_icon": {
				"label": "App Icon",
				"size": Vector2i(1024, 1024),
				"required": true,
				"alpha": ALPHA_NONE,
				"note": "PNG, sRGB or P3, no alpha. Square - Apple rounds the corners for you.",
			},
			"iphone_6_9_portrait": {
				"label": "iPhone 6.9\" - Portrait",
				"size": Vector2i(1320, 2868),
				"required": true,
				"alpha": ALPHA_NONE,
				"note": "Required for iPhone apps. Apple scales the smaller iPhone sizes from this.",
			},
			"iphone_6_9_landscape": {
				"label": "iPhone 6.9\" - Landscape",
				"size": Vector2i(2868, 1320),
				"required": false,
				"alpha": ALPHA_NONE,
				"note": "Use instead of the portrait size for landscape games.",
			},
			"ipad_13_portrait": {
				"label": "iPad 13\" - Portrait",
				"size": Vector2i(2064, 2752),
				"required": false,
				"alpha": ALPHA_NONE,
				"note": "Required if the app runs on iPad. Apple scales the smaller iPad sizes from this.",
			},
			"ipad_13_landscape": {
				"label": "iPad 13\" - Landscape",
				"size": Vector2i(2752, 2064),
				"required": false,
				"alpha": ALPHA_NONE,
				"note": "Use instead of the portrait size for landscape games.",
			},
			"mac": {
				"label": "Mac Screenshot",
				"size": Vector2i(2880, 1800),
				"required": false,
				"alpha": ALPHA_NONE,
				"note": "Required for Mac apps. Must be 16:10 - 1280x800, 1440x900, 2560x1600 or 2880x1800.",
			},
		},
	},
}

static var _preset_ids: PackedStringArray = PackedStringArray()


#region Stores

## Store ids in table order, e.g. ["steam", "itch", ...].
static func store_ids() -> PackedStringArray:
	return PackedStringArray(STORES.keys())


## The table entry for [param store_id], or an empty dictionary if it is not
## a store we know about.
static func get_store(store_id: String) -> Dictionary:
	return STORES.get(store_id, {})


static func store_label(store_id: String) -> String:
	var store := get_store(store_id)
	return store.get("label", store_id) if store else store_id


## Comma-separated labels for a [constant PROPERTY_HINT_ENUM] int property.
## Index 0 is "Custom"; the rest line up with [method store_ids].
static func store_hint_string() -> String:
	var labels := PackedStringArray(["Custom"])
	for store_id in store_ids():
		labels.append(store_label(store_id))
	return ",".join(labels)


static func store_index(store_id: String) -> int:
	var index := Array(store_ids()).find(store_id)
	return index + 1 if index >= 0 else 0


static func store_at(index: int) -> String:
	var ids := store_ids()
	return ids[index - 1] if index >= 1 and index <= ids.size() else CUSTOM_ID

#endregion


#region Presets

## Every preset id across every store, in table order. Does not include
## [constant CUSTOM_ID].
static func preset_ids() -> PackedStringArray:
	if _preset_ids.is_empty():
		for store_id in STORES:
			for asset_id in STORES[store_id]["assets"]:
				_preset_ids.append(store_id + ID_SEPARATOR + asset_id)
	return _preset_ids


## Preset ids belonging to one store, in table order.
static func preset_ids_for_store(store_id: String) -> PackedStringArray:
	var ids := PackedStringArray()
	var store := get_store(store_id)
	if store.is_empty():
		return ids
	for asset_id in store["assets"]:
		ids.append(store_id + ID_SEPARATOR + asset_id)
	return ids


## The spec dictionary for [param preset_id], or an empty dictionary for
## [constant CUSTOM_ID] and for ids that are no longer in the table.
static func get_preset(preset_id: String) -> Dictionary:
	var parts := preset_id.split(ID_SEPARATOR, false)
	if parts.size() != 2:
		return {}
	var store := get_store(parts[0])
	if store.is_empty():
		return {}
	return store["assets"].get(parts[1], {})


static func has_preset(preset_id: String) -> bool:
	return not get_preset(preset_id).is_empty()


## The store half of a preset id, or "" if there isn't one.
static func store_of(preset_id: String) -> String:
	var parts := preset_id.split(ID_SEPARATOR, false)
	return parts[0] if parts.size() == 2 else CUSTOM_ID


## The asset half of a preset id, or "" if there isn't one.
static func asset_of(preset_id: String) -> String:
	var parts := preset_id.split(ID_SEPARATOR, false)
	return parts[1] if parts.size() == 2 else CUSTOM_ID


static func preset_size(preset_id: String) -> Vector2i:
	return get_preset(preset_id).get("size", Vector2i.ZERO)


static func preset_alpha(preset_id: String) -> String:
	return get_preset(preset_id).get("alpha", ALPHA_OPTIONAL)


## Human-readable name for a dropdown entry. Deliberately comma-free: these
## are joined into a [constant PROPERTY_HINT_ENUM] hint string.
static func preset_label(preset_id: String, include_store: bool = false) -> String:
	var preset := get_preset(preset_id)
	if preset.is_empty():
		return "Custom" if preset_id == CUSTOM_ID else "%s (missing from the preset table)" % preset_id
	var size: Vector2i = preset["size"]
	var label: String = preset["label"]
	if include_store:
		label = "%s - %s" % [store_label(store_of(preset_id)), label]
	if not preset.get("required", false):
		label += " (optional)"
	return "%s  %dx%d" % [label, size.x, size.y]

#endregion


#region Output paths

## Folder name a store's images are written into, relative to the output root.
static func store_folder(store_id: String) -> String:
	var store := get_store(store_id)
	return store.get("folder", store_id) if store else store_id


## Lowercases and strips anything that has no business being in a file or
## folder name, so node names can be used as paths safely.
static func slugify(text: String) -> String:
	var slug := ""
	for character in text.strip_edges().to_lower():
		if character.is_valid_identifier() or character.is_valid_int() or character == "_":
			slug += character
		elif character == "-" or character == ".":
			slug += character
		else:
			slug += "_"
	while slug.contains("__"):
		slug = slug.replace("__", "_")
	return slug.strip_edges(true, true).lstrip("_").rstrip("_")

#endregion
